export const ADD_TO_CART="ADD_TO_CART";
export const ADD_TO_ORDER="ADD_TO_ORDER";
export const ADD_PRODUCTS='ADD_PRODUCTS';
export const INCREMENT='INCREMENT';
export const DECREMENT='DECREMENT';
export const USER_VALIDATION='USER_VALIDATION';